[[IgnoredVulns]]
id = "GHSA-h5c3-5r3r-rr8q"
reason = "Affected part not used in code"

[[IgnoredVulns]]
id = "GHSA-rmvr-2pp2-xj38"
reason = "Affected part not used in code"

[[IgnoredVulns]]
id = "GHSA-xx4v-prfh-6cgc"
reason = "Affected part not used in code"